Repository reliforp/reli-prof, pull requests merged in 2023-11, with the labels that each got.

#300 fixed to use getPointerType() to get the pointed type
  src/Lib/Process/Pointer/Pointer.php
Labels: cleanup

#301 Refactor the implementation of Pointer
  src/Lib/Process/Pointer/Pointer.php
  src/Lib/Process/Pointer/RemoteProcessDereferencer.php
Labels: cleanup

#302 Add support for dereferencing types using a subtype of dereferencables
  src/Lib/Process/Pointer/PointedTypeResolver.php
  src/Lib/Process/Pointer/Pointer.php
  src/Lib/Process/Pointer/RemoteProcessDereferencer.php
Labels: enhancement

#303 Add a missing annotation in Pointer::indexedAt()
  src/Lib/Process/Pointer/Pointer.php
Labels: cleanup

#304 add getPointer() to Dereferencable
  src/Lib/PhpInternals/Types/C/RawDouble.php
  src/Lib/PhpInternals/Types/C/RawInt32.php
  src/Lib/PhpInternals/Types/C/RawString.php
  src/Lib/PhpInternals/Types/Php/SapiGlobalsStruct.php
  src/Lib/PhpInternals/Types/Zend/Bucket.php
  src/Lib/PhpInternals/Types/Zend/ZendArray.php
  src/Lib/PhpInternals/Types/Zend/ZendClassEntry.php
  src/Lib/PhpInternals/Types/Zend/ZendExecuteData.php
  src/Lib/PhpInternals/Types/Zend/ZendExecutorGlobals.php
  src/Lib/PhpInternals/Types/Zend/ZendFunction.php
  src/Lib/PhpInternals/Types/Zend/ZendModuleEntry.php
  src/Lib/PhpInternals/Types/Zend/ZendOp.php
  src/Lib/PhpInternals/Types/Zend/ZendString.php
  src/Lib/Process/Pointer/Dereferencable.php
  tests/Lib/PhpInternals/Types/Zend/ZendStringTest.php
Labels: enhancement

#305 Simplify the implementation getting raw strings from ZendStrings
  src/Lib/PhpInternals/Types/Zend/ZendArray.php
  src/Lib/PhpInternals/Types/Zend/ZendClassEntry.php
  src/Lib/PhpInternals/Types/Zend/ZendFunction.php
  src/Lib/PhpInternals/Types/Zend/ZendOpArray.php
  src/Lib/PhpInternals/Types/Zend/ZendString.php
  tests/Lib/PhpInternals/Types/Zend/ZendStringTest.php
Labels: cleanup

#306 Support more format of memory maps
  src/Lib/Process/MemoryMap/ProcessMemoryMapParser.php
Labels: enhancement

#307 Migrate phpunit configuration to new schema
  phpunit.xml.dist
Labels: cleanup

#319 Fix the php version in the output of the memory profiler
  src/Command/Inspector/MemoryCommand.php
Labels: bug

#321 Add more about the memory profiler
  README.md
Labels: documentation

#327 Separate out contexts for object properties
  src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/ObjectPropertiesContext.php
Labels: enhancement

#328 Add caution to the README to not upload the output of memory dump, and the feature is experimental
  README.md
Labels: documentation

#329 Append the file name and start/end line to the function name to distinguish closures in the same file.
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV70.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV71.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV72.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV73.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV74.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV80.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV81.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV82.php
  src/Lib/PhpInternals/Constants/VersionAwareConstants.php
  src/Lib/PhpInternals/Types/Zend/ZendExecuteData.php
  src/Lib/PhpInternals/Types/Zend/ZendFunction.php
  src/Lib/PhpInternals/Types/Zend/ZendOpArray.php
  src/Lib/PhpProcessReader/CallTraceReader/CallTraceReader.php
  src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php
Labels: enhancement

#330 Improve the handling of function names
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV70.php
  src/Lib/PhpInternals/Constants/VersionAwareConstants.php
  src/Lib/PhpInternals/Types/Zend/ZendExecuteData.php
  src/Lib/PhpProcessReader/CallTraceReader/CallTraceReader.php
  src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/FunctionDefinitionContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/InternalFunctionDefinitionContext.php
Labels: enhancement

#331 Pretend PHP 7.0 for finding the module registry
  src/Lib/PhpProcessReader/PhpVersionDetector.php
Labels: enhancement

#332 Use the chunk that the current_execute_data resides in for finding the main chunk
  src/Lib/PhpInternals/Types/Zend/ZendMmChunk.php
  src/Lib/PhpProcessReader/PhpZendMemoryManagerChunkFinder.php
Labels: enhancement

#333 Add #count field to grouping contexts
  src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/ArrayElementsContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/CallFrameVariableTableContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/CallFramesContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/ClassConstantsContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/ClassStaticPropertiesContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/DefinedClassesContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/DefinedFunctionsContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/GlobalConstantsContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/IncludedFilesContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/ObjectPropertiesContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/ObjectsStoreContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/PropertiesInfoContext.php
  tests/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollectorTest.php
Labels: enhancement, cleanup

#336 Add a document explaining the memory profiler
  README.md
  docs/memory-profiler.md
Labels: documentation

#337 Explain a way to capture memory_limit violations
  docs/memory-profiler.md
Labels: documentation

#338 Add more about the memory profiler
  docs/memory-profiler.md
Labels: documentation

#339 Add a bit more about the memory profiler
  docs/memory-profiler.md
Labels: documentation

#340 Add support for targeting PHP 8.3
  src/Inspector/Settings/TargetPhpSettings/TargetPhpSettings.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV83.php
  src/Lib/PhpInternals/Constants/VersionAwareConstants.php
  src/Lib/PhpInternals/Headers/v83.h
  src/Lib/PhpInternals/Opcodes/OpcodeFactory.php
  src/Lib/PhpInternals/Opcodes/OpcodeV83.php
  src/Lib/PhpInternals/ZendTypeReader.php
  src/Lib/PhpProcessReader/PhpGlobalsFinder.php
  src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php
Labels: enhancement

#341 Fix the assertion failure when live_range is null
  src/Lib/PhpInternals/Types/Zend/ZendOpArray.php
Labels: bug

#342 Fix the closure detection on targeting PHP 8.2
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV80.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV81.php
  src/Lib/PhpInternals/Constants/PhpInternalsConstantsV82.php
Labels: bug

#343 Add an option to toggle pretty-printing to the memory reader
  src/Command/Inspector/MemoryCommand.php
Labels: enhancement

#344 Remove unnecessary # from some keys
  docs/memory-profiler.md
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/CallFrameContext.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ReferenceContext/ScalarValueContext.php
  tests/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollectorTest.php
Labels: enhancement

#345 Add the tool version to the output of the memory reader
  src/Command/Inspector/MemoryCommand.php
  src/ReliProfiler.php
Labels: enhancement

#346 pcntl has been required for long now
  README.md
  docs/memory-profiler.md
Labels: documentation

#347 Add description about refcount to memory-profiler.md
  docs/memory-profiler.md
Labels: documentation

#348 Add minimal description about location_types_summary and class_objects_summary, and summary.php_version
  docs/memory-profiler.md
Labels: documentation

#349 Bump the version to 0.9.0
  src/ReliProfiler.php
Labels: documentation

#350 Fix the regex to find PHP 8.3 binaries on some environment
  src/Inspector/Settings/TargetPhpSettings/TargetPhpSettings.php
Labels: bug

#352 Fix error on the latest interpreter
  src/Lib/PhpInternals/Types/C/PointerArray.php
Labels: bug

#354 Fix the document for the memory reader
  docs/memory-profiler.md
Labels: documentation

#355 Fix outdated parts of the README
  README.md
Labels: documentation

#356 Fixed the problem of trying to read invalid entries in the objects_bucket
  src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php
Labels: bug

#357 Fixed the wrong type assertions in the ObjectClassAnalyzer
  src/Lib/PhpProcessReader/PhpMemoryReader/ObjectClassAnalyzer/ObjectClassAnalyzer.php
  src/Lib/PhpProcessReader/PhpMemoryReader/ObjectClassAnalyzer/ObjectClassAnalyzerResult.php
Labels: bug

#359 Add a troubleshooting section for the memory reader
  docs/memory-profiler.md
Labels: documentation

#360 Suppresses error output due to intended cancellations in the daemon mode
  src/Command/Inspector/DaemonCommand.php
  src/Command/Inspector/TopLikeCommand.php
Labels: bug

#363 Fix autoload path resolving when loaded as a dependency
  reli
Labels: bug

#365 Add a configuration option to the speedscope converter for the handling of utf8 errors
  src/Command/Converter/SpeedscopeCommand.php
  src/Converter/Speedscope/Settings/SpeedscopeConverterSettings.php
  src/Converter/Speedscope/Settings/SpeedscopeConverterSettingsException.php
  src/Converter/Speedscope/Settings/SpeedscopeConverterSettingsFromConsoleInput.php
  src/Converter/Speedscope/Settings/Utf8ErrorHandlingType.php
  src/Converter/Speedscope/SpeedscopeConverter.php
Labels: enhancement

#369 Use Composer\InstalledVersions to retrieve the installed version
  reli
  src/ReliProfiler.php
Labels: bug, enhancement
